import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/Header"; // Updated path
import Footer from "./component/Footer"; // Updated path

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <div className="pt-[12vh] md:pt-[12vh] lg:pt-[10vh] ">
          {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
